### ISSUE TITLE
Handoff Repair

### ISSUE THREAD

**Issue by galaxybomb23** [galaxybomb23/ECE-461-Phase-2#1]
This issue it designed for the handoff Assessment and Repair. The team will meet and discuss any issues with the prior project's implementation. Issues are to be noted here then a repair branch will be created to fix these issues

Deliverable:

- [x] Assessment document of issues
- [ ] PR that fixes identified issues

**Comment by RushilShaw** [comment]
Is it possible to receive this team's graded rubric so we know exactly where points were taken off and what we need to fix?

**Comment by Coop8** [comment]
Updated License to clone repo locally and rewrote tests to mock local data.

**Comment by Coop8** [comment]
> Is it possible to receive this team's graded rubric so we know exactly where points were taken off and what we need to fix?

Email Huiyun Peng and CC Prof. Davis to see what areas they struggled with without asking how much they struggled.

**Comment by galaxybomb23** [comment]
### Repair Assessment

- [ ] Fix one metric to clone locally
- [ ] Update License to check compatibility
- [ ] Update tests for License
- [ ] Update Netscore to be 0 when license is 0
- [ ] Fix logger  (maybe use winston)
- [ ] fix install command
- [ ] Cleanup unused dependencies/imports

**Comment by Coop8** [comment]
I cleaned up imports, need to clean up dependencies like sqlite3

**Comment by galaxybomb23** [comment]
NDJSON output seems ok. "jq" is able to parse the output no problem
Resolving "Look into JSON output"

**Comment by iBoot32** [comment]
Added test to ensure netscore=0 when license=0, and test to ensure netscore=1 when all metrics-1. Seems to test net score pretty sufficiently
